CREATE TABLE beer (
    beer_id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE,
    description VARCHAR(2500) NOT NULL
);

CREATE TABLE temperature (
    temperature_id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `value` INT(10) UNSIGNED NOT NULL,
    unit VARCHAR(100) NOT NULL,
    beer_id INT(10) UNSIGNED NOT NULL,
    CONSTRAINT fk_temperature_beer_id FOREIGN KEY (beer_id) REFERENCES beer(beer_id)
    ON UPDATE CASCADE ON DELETE CASCADE
);